<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>StarWatch</title>
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
		<link href="css\style.css" rel="stylesheet">
		<script src="javascript\frontend.js"></script>
		<script src="javascript\atualizar.js"></script>
	</head>
	<body>
		<nav class="navbar navbar-expand-lg bg-navbar">
			<div class="container-fluid">
				<a class="navbar-brand" href="index.php"><img src="img\claquete.png" width="40" height="40"></a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
					<div class="navbar-nav">
						<a class="nav-link active" href="index.php">Home</a>
						<a class="nav-link" href="adicionar.phtml">Adicionar Filmes e Séries</a>
						<a class="nav-link" href="listar.phtml">Meus Filmes e Séries</a>
					</div>
				</div>
			</div>
		</nav>

		<div class="container col-xxl-8 px-4 py-3">
			<div class="row flex-lg-row-reverse align-items-center g-5 py-5">
			<div class="col-10 col-sm-8 col-lg-6">
					<img src="img\img-padrao.png" id="fotoCapaCarregada" class="mx-auto p-3" style="display: block;" width="300" height="400" loading="lazy">
					<div class="mx-auto" style="display: grid; width: 300px;">
						<input type="button" class="btn btn-primary btn-lg" id="escolherArquivo" value="Escolher capa">
					</div>
					<input class="form-control" type="file" id="fotoCapa" style="display: none;">
				</div>

				<div class="col-lg-6">
					<h5 class="fw-bold text-body-emphasis mb-3">Atualize seu filme/série</h5>
					<div class="mb-3">
						<input type="text" class="form-control" id="titulo" placeholder="Título">
						<div class="btn-group mt-1" role="group">
							<input type="radio" class="btn-check" name="tipoFilmeSerie" id="filme" autocomplete="off" onchange="updateLabel(this)">
							<label class="btn btn-outline-primary" for="filme">Filmes</label>

							<input type="radio" class="btn-check" name="tipoFilmeSerie" id="serie" autocomplete="off" onchange="updateLabel(this)">
							<label class="btn btn-outline-primary" for="serie">Séries</label>
						</div>
						<br><br>
						<input type="text" class="form-control" id="anoLancamento" placeholder="Ano de Lançamento"><br>

						<select class="form-select" multiple id="genero">
							
						</select><br>

						<textarea class="form-control" id="sinopse" rows="3" placeholder="Sinopse"></textarea><br>

						<textarea class="form-control" id="opiniao" rows="3" placeholder="Opinião"></textarea>

						<div class="rating">
							<input type="radio" id="star5" name="rating" value="5">
							<label for="star5">&#9733;</label>
							<input type="radio" id="star4" name="rating" value="4">
							<label for="star4">&#9733;</label>
							<input type="radio" id="star3" name="rating" value="3">
							<label for="star3">&#9733;</label>
							<input type="radio" id="star2" name="rating" value="2">
							<label for="star2">&#9733;</label>
							<input type="radio" id="star1" name="rating" value="1">
							<label for="star1">&#9733;</label>
						</div>
						<br>
						<button type="button" id="btnAtualizar" class="btn btn-primary btn-lg px-4 me-md-2">Atualizar</button>
						<button type="button" id="btnExcluirToggle" class="btn btn-primary btn-lg px-4 me-md-2" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Excluir</button>

						<!-- Modal -->
						<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
						<div class="modal-dialog">
							<div class="modal-content">
							<div class="modal-header">
								<h1 class="modal-title fs-5" id="staticBackdropLabel">Tem certeza que deseja excluir esse título?</h1>
								<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
							</div>
							<div class="modal-body">
								Ao clicar em OK você confirma que o Título selecionado será excluído e não será mais apresentado na Lista dos seus Filmes e Séries
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
								<button type="button" id="btnExcluir" class="btn btn-primary">OK</button>
							</div>
							</div>
						</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
	</body>
</html>